### ISSUE TITLE
Unused parameter

### ISSUE THREAD

**Issue by criszacca** [nunomaduro/phpinsights#257]
| Q                      | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| Library version  | latest

Hi guys. First of all, **thank for this awesome package**!

I'm using this package with Laravel 5.8 and in some cases (responses or builders) the implementation of Laravel's API resources forces me to indicate some variables that aren't used into the function but it needs to be declared. 

So I think of something like this will be helpful:

```php
\SlevomatCodingStandard\Sniffs\Functions\UnusedParameterSniff::class => [
            'excludedVariables' => [
                '$model',
                '$request'
            ]
        ]
```

This way we can keep the files to be checked for other issues

**Comment by olivernybroe** [comment]
Hmm not sure how good a solution that would be, as I could name the variable whatever I want and then it would show a error again.

However you can silence it with `@phpcsSuppress` in the doc blocks. 

I would however like to find a really viable solution for this.

**Comment by tarlepp** [comment]
I have been seeing this a lot with classes that extends some another class and those methods are containing  those parameters on that base implementation - I really cannot remove those (order won't be the same and so on..) and same goes for classes that implements some interface that has "extra" parameters that I'm not using at all.

adding that `@phpcsSuppress` seems a bit weird - imho - just because eg. ecs is working just fine... although I'm using custom `easy-coding-standard.yaml` file and that said I'm assuming that PhpInsight should also use that configuration - right?

**Comment by olivernybroe** [comment]
@tarlepp We actually don't use ECS anymore, so no we do not use ecs config files, but we also didn't do that before.

So you are saying that with ECS it works fine for you, by that I assume you mean it does not show the messages about unused parameter? Do you have any idea on how they solved the problem?

**Comment by nunomaduro** [comment]
@criszacca Fell free to make a pull request with this feature. Thanks!
