### ISSUE TITLE
"SlevomatCodingStandard.Arrays.TrailingArrayComma" does not exist

### ISSUE THREAD

**Issue by olivernybroe** [nunomaduro/phpinsights#401]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Library version  | master

When running `bin/phpinsights` on this repository it runs correctly, however when I try to do the following:
```bash
cd bin
./phpinsights analyse ..
```
It results in 
```
In Ruleset.php line 830:
                                                                                      
  Referenced sniff "SlevomatCodingStandard.Arrays.TrailingArrayComma" does not exist  
```

**Comment by Jibbarth** [comment]
Seems to be a problem with PHPCS.

Able to reproduce if I do 
```
cd vendor/bin
./phpcs
```

=> 
```
ERROR: Referenced sniff "SlevomatCodingStandard.Arrays.TrailingArrayComma" does not exist

Run "phpcs --help" for usage information
```

When deleting .php_cs.xml.dist, it works.

However, I think it's happen because our phpcs config file contains this : 

```
    <config name="installed_paths" value="vendor/slevomat/coding-standard"/>
```

When we launch tools in other directory, when building a Ruleset, phpcs search this dir in current working directory... :slightly_frowning_face: 

That could be fix by adding `$config->restoreDefaults();` in FileFactory. 

But by doing this, I get a PHP Warning: 

```
PHP Warning:  Use of undefined constant T_CLOSURE - assumed 'T_CLOSURE' (this will throw an Error in a future version of PHP) in ~/phpinsights/vendor/squizlabs/php_codesniffer/src/Standards/PEAR/Sniffs/Functions/ValidDefaultValueSniff.php on line 28

```
