### ISSUE TITLE
Details of globals accesses

### ISSUE THREAD

**Issue by ibrunotome** [nunomaduro/phpinsights#73]
<img width="299" alt="Screen Shot 2019-05-16 at 14 37 44" src="https://user-images.githubusercontent.com/4256471/57874982-2d70dc80-77e8-11e9-8afc-cb998ed9efd6.png">

And that's it, no more details, even with -v

Can you help with some method to see more details of it?

**Comment by nunomaduro** [comment]
This is a feature request, someone would like to help on this? To solve it:

1. Go to [Analyser](https://github.com/nunomaduro/phpinsights/blob/master/src/Domain/Analyser.php) and instead of increment global access we need push the global access information to an array on the [Collector](https://github.com/nunomaduro/phpinsights/blob/master/src/Domain/Collector.php).
2. Adapt metric [ForbiddenGlobals](https://github.com/nunomaduro/phpinsights/blob/master/src/Domain/Insights/ForbiddenGlobals.php) implementing the [HasDetails](https://github.com/nunomaduro/phpinsights/blob/master/src/Domain/Contracts/HasDetails.php) interface.

**Comment by Morkhusz** [comment]
I'm working on it!
Any advice on how to structure the details message?

**Comment by nunomaduro** [comment]
I trust you for that message. 😊
